default_chain: stride-testnet
chains:
  gaia-testnet:
    key: timemachine
    chain-id: GAIA
    rpc-addr: http://127.0.0.1:23657
    grpc-addr: http://149.102.142.82:23090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride-testnet:
    key: timemachine
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://127.0.0.1:16657      
    grpc-addr: http://149.102.142.82:16090    
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
